### ISSUE TITLE
зачем...

### ISSUE THREAD

**Issue by nyudenkov** [animusdev/whiteTG#136]

**Comment by NazarFogmann** [comment]
Надо....

**Comment by jammer312** [comment]
![екарный бабай](https://ic.pics.livejournal.com/rapitangnyy/60397330/34617/34617_900.jpg)

**Comment by nyudenkov** [comment]
> Надо....

for what..

**Comment by nyudenkov** [comment]
за что ты насилуешь его...

**Comment by ghost** [comment]
зачем ты насилуеш интебрей блин............................

**Comment by nyudenkov** [comment]
потому что могу..

**Comment by nyudenkov** [comment]
бля вк упал

**Comment by NazarFogmann** [comment]
41-45 можем повторить
