### ISSUE TITLE
Freezer machine board

### ISSUE THREAD

**Issue by EPOXINBLET** [animusdev/whiteTG#26]
При использовании отвёртки на плате охладителя газа (Freezer) плата становится безымянной. При установке платы в машину нужны те же детали что для Freezer'а. При этом после добавления всех компонентов и попытки закручивания машины отвёрткой ничего не происходит.

Описание багнутой платы: http://prntscr.com/geulr0
Машина с багнутой платой и всеми компонентами установленными, но завершить строительство который невозможно: http://prntscr.com/geum5l http://prntscr.com/geumqu

**Comment by NazarFogmann** [comment]
Пофикшено
