### ISSUE TITLE
привет

### ISSUE THREAD

**Issue by wwwwwwsas** [animusdev/whiteTG#73]
РАЗБАНЬТЕ Я БОЛЬШЕ НЕ БУДУ

**Comment by Difilex** [comment]
Жоктопус сосать

**Comment by nyudenkov** [comment]
Пошел нахуй дифилекс

**Comment by nyudenkov** [comment]
@wwwwwwsas почему ты в мою репу срёшь урод

**Comment by Difilex** [comment]
Сосаттттттттттттттттттт
