### ISSUE TITLE
Игровая валюта

### ISSUE THREAD

**Issue by fluffy228** [animusdev/whiteTG#90]
Issue reported from Round ID: 1765 (Main Russian Servers [SS13.RU] - White Dream)

Тут такая хуйня произошла. В общем, когда я попытался отправить на карго-шаттле кредиты (в форме Diamond Coins) на сумму 1500, у меня их хуй засчитали. Прошу разобраться, ёпта бля нахуй.

**Comment by jammer312** [comment]
Так там не в кредитах суть. Отправляй плазму, лут с лаваленда (от боссов) и предметы из РнД, чтоб очков набрать.

**Comment by koghs** [comment]
Надо было отправлять САМИ алмазы, а не коины. Так и задумано.

**Comment by ACCount12** [comment]
Нихера, и это уже пофиксили на стороне ТГшников.
